apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unknown
  namespace: traefik
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.secretStoreName }}
    kind: SecretStore
  target:
    name: {{ .Chart.Name }}
    creationPolicy: Owner
  data:
    - secretKey: NEW_FEATURE_ENABLED
      remoteRef:
        key: {{ .Values.gcp.secretName }}
        property: NEW_FEATURE_ENABLED
        version: latest       
        
